/**
 * Vercel 빌드 시 실행됩니다.
 * NEXT_PUBLIC_ 환경변수를 읽어 브라우저에서 접근 가능한 __env.js를 생성합니다.
 * 값이 없어도 앱이 중단되지 않습니다.
 */
const fs = require('fs');
const path = require('path');

const url = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

const output = `/* Auto-generated by scripts/build-env.js — DO NOT EDIT */
window.__SUPABASE_URL = ${JSON.stringify(url)};
window.__SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;

const outPath = path.join(__dirname, '..', '__env.js');
fs.writeFileSync(outPath, output, 'utf8');

if (url && key) {
  console.log('[build-env] ✅ Supabase 환경변수 주입 완료');
} else {
  console.warn('[build-env] ⚠️  NEXT_PUBLIC_SUPABASE_URL 또는 NEXT_PUBLIC_SUPABASE_ANON_KEY가 비어 있습니다.');
  console.warn('[build-env]    Vercel 대시보드 > Settings > Environment Variables 에서 값을 등록해주세요.');
}
